apiVersion: v1
kind: Service              # 1
metadata:
  name: react-frontend
spec:
  type: ClusterIP
  ports:
  - port: 6060               # 3
    protocol: TCP          # 4
    targetPort: 6060         # 5
  selector:                # 6
    app: react-app      # 7